# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: tests/protobuf/testing.proto
# plugin: grpclib.plugin.main
from abc import ABCMeta, abstractmethod

import grpclib.server
import grpclib.client
import grpclib.__public__

import tests.protobuf.testing_pb2


class BombedService(metaclass=ABCMeta):

    @abstractmethod
    async def Plaster(self, request, context):
        pass

    def __mapping__(self):
        return {
            '/BombedService/Plaster': grpclib.server.Method(
                self.Plaster,
                grpclib.__public__.Cardinality.UNARY_UNARY,
                tests.protobuf.testing_pb2.SavoysRequest,
                tests.protobuf.testing_pb2.SavoysReply,
            ),
        }


class BombedServiceStub:

    def __init__(self, channel):
        self.channel = channel

    Plaster = grpclib.client.UnaryUnaryCall(grpclib.client.Method(
        '/BombedService/Plaster',
        tests.protobuf.testing_pb2.SavoysRequest,
        tests.protobuf.testing_pb2.SavoysReply,
    ))
