# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protobuf/testing.proto
# plugin: asyncgrpc.plugin.main
from abc import ABCMeta, abstractmethod

import asyncgrpc.server
import asyncgrpc.client

import protobuf.testing_pb2


class BombedService(metaclass=ABCMeta):

    @abstractmethod
    async def Plaster(self, request, context):
        pass

    def __mapping__(self):
        return {
            '/BombedService/Plaster': asyncgrpc.server.Method(
                self.Plaster,
                protobuf.testing_pb2.SavoysRequest,
                protobuf.testing_pb2.SavoysReply,
            ),
        }


class BombedServiceStub:

    def __init__(self, channel):
        self.channel = channel

    Plaster = asyncgrpc.client.UnaryUnaryCall(asyncgrpc.client.Method(
        '/BombedService/Plaster',
        protobuf.testing_pb2.SavoysRequest,
        protobuf.testing_pb2.SavoysReply,
    ))
