# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: tests/protobuf/testing.proto
# plugin: grpclib.plugin.main
from abc import ABCMeta, abstractmethod

import grpclib.client
import grpclib.__public__

import tests.protobuf.testing_pb2


class BombedService(metaclass=ABCMeta):

    @abstractmethod
    async def Plaster(self, stream):
        pass

    @abstractmethod
    async def Benzine(self, stream):
        pass

    @abstractmethod
    async def Anginal(self, stream):
        pass

    @abstractmethod
    async def Devilry(self, stream):
        pass

    def __mapping__(self):
        return {
            '/BombedService/Plaster': grpclib.__public__.Handler(
                self.Plaster,
                grpclib.__public__.Cardinality.UNARY_UNARY,
                tests.protobuf.testing_pb2.SavoysRequest,
                tests.protobuf.testing_pb2.SavoysReply,
            ),
            '/BombedService/Benzine': grpclib.__public__.Handler(
                self.Benzine,
                grpclib.__public__.Cardinality.UNARY_STREAM,
                tests.protobuf.testing_pb2.SavoysRequest,
                tests.protobuf.testing_pb2.GoowyChunk,
            ),
            '/BombedService/Anginal': grpclib.__public__.Handler(
                self.Anginal,
                grpclib.__public__.Cardinality.STREAM_UNARY,
                tests.protobuf.testing_pb2.UnyoungChunk,
                tests.protobuf.testing_pb2.SavoysReply,
            ),
            '/BombedService/Devilry': grpclib.__public__.Handler(
                self.Devilry,
                grpclib.__public__.Cardinality.STREAM_STREAM,
                tests.protobuf.testing_pb2.UnyoungChunk,
                tests.protobuf.testing_pb2.GoowyChunk,
            ),
        }


class BombedServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Plaster = grpclib.client.UnaryUnaryMethod(
            channel,
            '/BombedService/Plaster',
            tests.protobuf.testing_pb2.SavoysRequest,
            tests.protobuf.testing_pb2.SavoysReply,
        )
        self.Benzine = grpclib.client.UnaryStreamMethod(
            channel,
            '/BombedService/Benzine',
            tests.protobuf.testing_pb2.SavoysRequest,
            tests.protobuf.testing_pb2.GoowyChunk,
        )
        self.Anginal = grpclib.client.StreamUnaryMethod(
            channel,
            '/BombedService/Anginal',
            tests.protobuf.testing_pb2.UnyoungChunk,
            tests.protobuf.testing_pb2.SavoysReply,
        )
        self.Devilry = grpclib.client.StreamStreamMethod(
            channel,
            '/BombedService/Devilry',
            tests.protobuf.testing_pb2.UnyoungChunk,
            tests.protobuf.testing_pb2.GoowyChunk,
        )
