# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: helloworld.proto
# plugin: asyncgrpc.plugin.main
from abc import ABCMeta, abstractmethod

import asyncgrpc.server
import asyncgrpc.client

import helloworld_pb2


class Greeter(metaclass=ABCMeta):

    @abstractmethod
    async def SayHello(self, request, context):
        pass

    def __mapping__(self):
        return {
            '/helloworld.Greeter/SayHello': asyncgrpc.server.Method(
                self.SayHello,
                helloworld_pb2.HelloRequest,
                helloworld_pb2.HelloReply,
            ),
        }


class GreeterStub:

    def __init__(self, channel):
        self.channel = channel

    SayHello = asyncgrpc.client.UnaryUnaryCall(asyncgrpc.client.Method(
        '/helloworld.Greeter/SayHello',
        helloworld_pb2.HelloRequest,
        helloworld_pb2.HelloReply,
    ))
