# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
# plugin: asyncgrpc.plugin.main

from asyncgrpc.handler import Method

import helloworld_pb2


class Greeter:
    __service__ = 'helloworld.Greeter'
    __methods__ = set()
    
    SayHello = \
        Method('SayHello',
               helloworld_pb2.HelloRequest,
               helloworld_pb2.HelloReply)
    __methods__.add(SayHello)
