# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: example/helloworld.proto
# plugin: grpclib.plugin.main
from abc import ABCMeta, abstractmethod

import grpclib.__public__

import example.helloworld_pb2


class Greeter(metaclass=ABCMeta):

    @abstractmethod
    async def SayHello(self, request, context):
        pass

    def __mapping__(self):
        return {
            '/helloworld.Greeter/SayHello': grpclib.__public__.Handler(
                self.SayHello,
                grpclib.__public__.Cardinality.UNARY_UNARY,
                example.helloworld_pb2.HelloRequest,
                example.helloworld_pb2.HelloReply,
            ),
        }


class GreeterStub:

    def __init__(self, channel):
        self.channel = channel

    SayHello = grpclib.__public__.CallDescriptor(grpclib.__public__.Method(
        '/helloworld.Greeter/SayHello',
        grpclib.__public__.Cardinality.UNARY_UNARY,
        example.helloworld_pb2.HelloRequest,
        example.helloworld_pb2.HelloReply,
    ))
