# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bombed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bombed.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x62ombed.proto\"\x1e\n\rSavoysRequest\x12\r\n\x05kyler\x18\x01 \x01(\t\"\x1d\n\x0bSavoysReply\x12\x0e\n\x06\x62\x65nito\x18\x01 \x01(\t\"\x1d\n\x0cUnyoungChunk\x12\r\n\x05whome\x18\x01 \x01(\t\"\x1c\n\nGoowyChunk\x12\x0e\n\x06\x62iomes\x18\x01 \x01(\t2\xb8\x01\n\x06\x42ombed\x12)\n\x07Plaster\x12\x0e.SavoysRequest\x1a\x0c.SavoysReply\"\x00\x12*\n\x07\x42\x65nzine\x12\x0e.SavoysRequest\x1a\x0b.GoowyChunk\"\x00\x30\x01\x12*\n\x07\x41nginal\x12\r.UnyoungChunk\x1a\x0c.SavoysReply\"\x00(\x01\x12+\n\x07\x44\x65vilry\x12\r.UnyoungChunk\x1a\x0b.GoowyChunk\"\x00(\x01\x30\x01\x62\x06proto3')
)




_SAVOYSREQUEST = _descriptor.Descriptor(
  name='SavoysRequest',
  full_name='SavoysRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='kyler', full_name='SavoysRequest.kyler', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=46,
)


_SAVOYSREPLY = _descriptor.Descriptor(
  name='SavoysReply',
  full_name='SavoysReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='benito', full_name='SavoysReply.benito', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=77,
)


_UNYOUNGCHUNK = _descriptor.Descriptor(
  name='UnyoungChunk',
  full_name='UnyoungChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='whome', full_name='UnyoungChunk.whome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=108,
)


_GOOWYCHUNK = _descriptor.Descriptor(
  name='GoowyChunk',
  full_name='GoowyChunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='biomes', full_name='GoowyChunk.biomes', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['SavoysRequest'] = _SAVOYSREQUEST
DESCRIPTOR.message_types_by_name['SavoysReply'] = _SAVOYSREPLY
DESCRIPTOR.message_types_by_name['UnyoungChunk'] = _UNYOUNGCHUNK
DESCRIPTOR.message_types_by_name['GoowyChunk'] = _GOOWYCHUNK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SavoysRequest = _reflection.GeneratedProtocolMessageType('SavoysRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAVOYSREQUEST,
  __module__ = 'bombed_pb2'
  # @@protoc_insertion_point(class_scope:SavoysRequest)
  ))
_sym_db.RegisterMessage(SavoysRequest)

SavoysReply = _reflection.GeneratedProtocolMessageType('SavoysReply', (_message.Message,), dict(
  DESCRIPTOR = _SAVOYSREPLY,
  __module__ = 'bombed_pb2'
  # @@protoc_insertion_point(class_scope:SavoysReply)
  ))
_sym_db.RegisterMessage(SavoysReply)

UnyoungChunk = _reflection.GeneratedProtocolMessageType('UnyoungChunk', (_message.Message,), dict(
  DESCRIPTOR = _UNYOUNGCHUNK,
  __module__ = 'bombed_pb2'
  # @@protoc_insertion_point(class_scope:UnyoungChunk)
  ))
_sym_db.RegisterMessage(UnyoungChunk)

GoowyChunk = _reflection.GeneratedProtocolMessageType('GoowyChunk', (_message.Message,), dict(
  DESCRIPTOR = _GOOWYCHUNK,
  __module__ = 'bombed_pb2'
  # @@protoc_insertion_point(class_scope:GoowyChunk)
  ))
_sym_db.RegisterMessage(GoowyChunk)



_BOMBED = _descriptor.ServiceDescriptor(
  name='Bombed',
  full_name='Bombed',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=141,
  serialized_end=325,
  methods=[
  _descriptor.MethodDescriptor(
    name='Plaster',
    full_name='Bombed.Plaster',
    index=0,
    containing_service=None,
    input_type=_SAVOYSREQUEST,
    output_type=_SAVOYSREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Benzine',
    full_name='Bombed.Benzine',
    index=1,
    containing_service=None,
    input_type=_SAVOYSREQUEST,
    output_type=_GOOWYCHUNK,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Anginal',
    full_name='Bombed.Anginal',
    index=2,
    containing_service=None,
    input_type=_UNYOUNGCHUNK,
    output_type=_SAVOYSREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Devilry',
    full_name='Bombed.Devilry',
    index=3,
    containing_service=None,
    input_type=_UNYOUNGCHUNK,
    output_type=_GOOWYCHUNK,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOMBED)

DESCRIPTOR.services_by_name['Bombed'] = _BOMBED

# @@protoc_insertion_point(module_scope)
