# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: bombed.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import bombed_pb2


class BombedBase(abc.ABC):

    @abc.abstractmethod
    async def Plaster(self, stream):
        pass

    @abc.abstractmethod
    async def Benzine(self, stream):
        pass

    @abc.abstractmethod
    async def Anginal(self, stream):
        pass

    @abc.abstractmethod
    async def Devilry(self, stream):
        pass

    def __mapping__(self):
        return {
            '/Bombed/Plaster': grpclib.const.Handler(
                self.Plaster,
                grpclib.const.Cardinality.UNARY_UNARY,
                bombed_pb2.SavoysRequest,
                bombed_pb2.SavoysReply,
            ),
            '/Bombed/Benzine': grpclib.const.Handler(
                self.Benzine,
                grpclib.const.Cardinality.UNARY_STREAM,
                bombed_pb2.SavoysRequest,
                bombed_pb2.GoowyChunk,
            ),
            '/Bombed/Anginal': grpclib.const.Handler(
                self.Anginal,
                grpclib.const.Cardinality.STREAM_UNARY,
                bombed_pb2.UnyoungChunk,
                bombed_pb2.SavoysReply,
            ),
            '/Bombed/Devilry': grpclib.const.Handler(
                self.Devilry,
                grpclib.const.Cardinality.STREAM_STREAM,
                bombed_pb2.UnyoungChunk,
                bombed_pb2.GoowyChunk,
            ),
        }


class BombedStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Plaster = grpclib.client.UnaryUnaryMethod(
            channel,
            '/Bombed/Plaster',
            bombed_pb2.SavoysRequest,
            bombed_pb2.SavoysReply,
        )
        self.Benzine = grpclib.client.UnaryStreamMethod(
            channel,
            '/Bombed/Benzine',
            bombed_pb2.SavoysRequest,
            bombed_pb2.GoowyChunk,
        )
        self.Anginal = grpclib.client.StreamUnaryMethod(
            channel,
            '/Bombed/Anginal',
            bombed_pb2.UnyoungChunk,
            bombed_pb2.SavoysReply,
        )
        self.Devilry = grpclib.client.StreamStreamMethod(
            channel,
            '/Bombed/Devilry',
            bombed_pb2.UnyoungChunk,
            bombed_pb2.GoowyChunk,
        )
