# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dummy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x64ummy.proto\x12\x05\x64ummy\"\x1d\n\x0c\x44ummyRequest\x12\r\n\x05value\x18\x01 \x01(\t\"\x1b\n\nDummyReply\x12\r\n\x05value\x18\x01 \x01(\t2\xfa\x01\n\x0c\x44ummyService\x12\x36\n\nUnaryUnary\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00\x12\x39\n\x0bUnaryStream\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00\x30\x01\x12\x39\n\x0bStreamUnary\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00(\x01\x12<\n\x0cStreamStream\x12\x13.dummy.DummyRequest\x1a\x11.dummy.DummyReply\"\x00(\x01\x30\x01\x62\x06proto3')



_DUMMYREQUEST = DESCRIPTOR.message_types_by_name['DummyRequest']
_DUMMYREPLY = DESCRIPTOR.message_types_by_name['DummyReply']
DummyRequest = _reflection.GeneratedProtocolMessageType('DummyRequest', (_message.Message,), {
  'DESCRIPTOR' : _DUMMYREQUEST,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:dummy.DummyRequest)
  })
_sym_db.RegisterMessage(DummyRequest)

DummyReply = _reflection.GeneratedProtocolMessageType('DummyReply', (_message.Message,), {
  'DESCRIPTOR' : _DUMMYREPLY,
  '__module__' : 'dummy_pb2'
  # @@protoc_insertion_point(class_scope:dummy.DummyReply)
  })
_sym_db.RegisterMessage(DummyReply)

_DUMMYSERVICE = DESCRIPTOR.services_by_name['DummyService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DUMMYREQUEST._serialized_start=22
  _DUMMYREQUEST._serialized_end=51
  _DUMMYREPLY._serialized_start=53
  _DUMMYREPLY._serialized_end=80
  _DUMMYSERVICE._serialized_start=83
  _DUMMYSERVICE._serialized_end=333
# @@protoc_insertion_point(module_scope)
