# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dummy_pb2 as dummy__pb2


class DummyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UnaryUnary = channel.unary_unary(
        '/dummy.DummyService/UnaryUnary',
        request_serializer=dummy__pb2.DummyRequest.SerializeToString,
        response_deserializer=dummy__pb2.DummyReply.FromString,
        )
    self.UnaryStream = channel.unary_stream(
        '/dummy.DummyService/UnaryStream',
        request_serializer=dummy__pb2.DummyRequest.SerializeToString,
        response_deserializer=dummy__pb2.DummyReply.FromString,
        )
    self.StreamUnary = channel.stream_unary(
        '/dummy.DummyService/StreamUnary',
        request_serializer=dummy__pb2.DummyRequest.SerializeToString,
        response_deserializer=dummy__pb2.DummyReply.FromString,
        )
    self.StreamStream = channel.stream_stream(
        '/dummy.DummyService/StreamStream',
        request_serializer=dummy__pb2.DummyRequest.SerializeToString,
        response_deserializer=dummy__pb2.DummyReply.FromString,
        )


class DummyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UnaryUnary(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UnaryStream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamUnary(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamStream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DummyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UnaryUnary': grpc.unary_unary_rpc_method_handler(
          servicer.UnaryUnary,
          request_deserializer=dummy__pb2.DummyRequest.FromString,
          response_serializer=dummy__pb2.DummyReply.SerializeToString,
      ),
      'UnaryStream': grpc.unary_stream_rpc_method_handler(
          servicer.UnaryStream,
          request_deserializer=dummy__pb2.DummyRequest.FromString,
          response_serializer=dummy__pb2.DummyReply.SerializeToString,
      ),
      'StreamUnary': grpc.stream_unary_rpc_method_handler(
          servicer.StreamUnary,
          request_deserializer=dummy__pb2.DummyRequest.FromString,
          response_serializer=dummy__pb2.DummyReply.SerializeToString,
      ),
      'StreamStream': grpc.stream_stream_rpc_method_handler(
          servicer.StreamStream,
          request_deserializer=dummy__pb2.DummyRequest.FromString,
          response_serializer=dummy__pb2.DummyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dummy.DummyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
